// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahilPlanProje.WebApi.Context;

#nullable disable

namespace SahilPlanProje.WebApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260526034049_AddDistrictGroupNo")]
    partial class AddDistrictGroupNo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("country_code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("plate_code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.District", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("city_id")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("district_group_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<short>("district_no")
                        .HasColumnType("smallint");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_central")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("city_id");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDefinition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("city_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("district_id")
                        .HasColumnType("int");

                    b.Property<bool>("has_vat")
                        .HasColumnType("bit");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("tahakkuk_department_id")
                        .HasColumnType("int");

                    b.Property<int?>("tahakkuk_directorate_id")
                        .HasColumnType("int");

                    b.Property<int?>("tahakkuk_fee_sub_subject_id")
                        .HasColumnType("int");

                    b.Property<int>("tahakkuk_fee_subject_id")
                        .HasColumnType("int");

                    b.Property<int>("tahakkuk_institution_id")
                        .HasColumnType("int");

                    b.Property<int?>("tahakkuk_scale_id")
                        .HasColumnType("int");

                    b.Property<int>("tahakkuk_year_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("city_id");

                    b.HasIndex("district_id");

                    b.HasIndex("tahakkuk_department_id");

                    b.HasIndex("tahakkuk_directorate_id");

                    b.HasIndex("tahakkuk_fee_sub_subject_id");

                    b.HasIndex("tahakkuk_fee_subject_id");

                    b.HasIndex("tahakkuk_institution_id");

                    b.HasIndex("tahakkuk_scale_id");

                    b.HasIndex("tahakkuk_year_id");

                    b.ToTable("TahakkukDefinitions", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDepartment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("tahakkuk_institution_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_institution_id");

                    b.ToTable("TahakkukDepartments", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("tahakkuk_department_id")
                        .HasColumnType("int");

                    b.Property<int>("tahakkuk_institution_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_department_id");

                    b.HasIndex("tahakkuk_institution_id");

                    b.ToTable("TahakkukDirectorates");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubSubject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("tahakkuk_fee_subject_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_fee_subject_id");

                    b.ToTable("TahakkukFeeSubSubjects", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("TahakkukFeeSubjects", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukInstitution", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("TahakkukInstitutions", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukScale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("TahakkukScales", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukYear", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TahakkukYears", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.District", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.City", "city")
                        .WithMany("districts")
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDefinition", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.City", "city")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahilPlanProje.WebApi.Entities.District", "district")
                        .WithMany()
                        .HasForeignKey("district_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukDepartment", "tahakkuk_department")
                        .WithMany()
                        .HasForeignKey("tahakkuk_department_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", "tahakkuk_directorate")
                        .WithMany()
                        .HasForeignKey("tahakkuk_directorate_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukFeeSubSubject", "tahakkuk_fee_sub_subject")
                        .WithMany()
                        .HasForeignKey("tahakkuk_fee_sub_subject_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", "tahakkuk_fee_subject")
                        .WithMany()
                        .HasForeignKey("tahakkuk_fee_subject_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukInstitution", "tahakkuk_institution")
                        .WithMany()
                        .HasForeignKey("tahakkuk_institution_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukScale", "tahakkuk_scale")
                        .WithMany()
                        .HasForeignKey("tahakkuk_scale_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukYear", "tahakkuk_year")
                        .WithMany()
                        .HasForeignKey("tahakkuk_year_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("city");

                    b.Navigation("district");

                    b.Navigation("tahakkuk_department");

                    b.Navigation("tahakkuk_directorate");

                    b.Navigation("tahakkuk_fee_sub_subject");

                    b.Navigation("tahakkuk_fee_subject");

                    b.Navigation("tahakkuk_institution");

                    b.Navigation("tahakkuk_scale");

                    b.Navigation("tahakkuk_year");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDepartment", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukInstitution", "tahakkuk_institution")
                        .WithMany()
                        .HasForeignKey("tahakkuk_institution_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_institution");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukDepartment", "tahakkuk_department")
                        .WithMany()
                        .HasForeignKey("tahakkuk_department_id");

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukInstitution", "tahakkuk_institution")
                        .WithMany()
                        .HasForeignKey("tahakkuk_institution_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_department");

                    b.Navigation("tahakkuk_institution");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubSubject", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", "tahakkuk_fee_subject")
                        .WithMany()
                        .HasForeignKey("tahakkuk_fee_subject_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tahakkuk_fee_subject");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.City", b =>
                {
                    b.Navigation("districts");
                });
#pragma warning restore 612, 618
        }
    }
}
