// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahilPlanProje.WebApi.Context;

#nullable disable

namespace SahilPlanProje.WebApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260524065312_mig10")]
    partial class mig10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("country_code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("plate_code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.District", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("city_id")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<short>("district_no")
                        .HasColumnType("smallint");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_central")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("city_id");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDepartment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("tahakkuk_institution_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_institution_id");

                    b.ToTable("TahakkukDepartments", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("tahakkuk_department_id")
                        .HasColumnType("int");

                    b.Property<int>("tahakkuk_institution_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_department_id");

                    b.HasIndex("tahakkuk_institution_id");

                    b.ToTable("TahakkukDirectorates", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("TahakkukFeeSubjects", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukInstitution", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("TahakkukInstitutions", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukScale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("TahakkukScales", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukYear", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TahakkukYears", (string)null);
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.Test", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Test1");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.District", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.City", "city")
                        .WithMany("districts")
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDepartment", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukInstitution", "tahakkuk_institution")
                        .WithMany()
                        .HasForeignKey("tahakkuk_institution_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_institution");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukDepartment", "tahakkuk_department")
                        .WithMany()
                        .HasForeignKey("tahakkuk_department_id");

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukInstitution", "tahakkuk_institution")
                        .WithMany()
                        .HasForeignKey("tahakkuk_institution_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_department");

                    b.Navigation("tahakkuk_institution");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.City", b =>
                {
                    b.Navigation("districts");
                });
#pragma warning restore 612, 618
        }
    }
}
