// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahilPlanProje.WebApi.Context;

#nullable disable

namespace SahilPlanProje.WebApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260515035031_mig3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("plate_code")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.District", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("city_id")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<short>("district_no")
                        .HasColumnType("smallint");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_central")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("city_id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.Feature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("video_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDefinition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("fee_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("fee_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("has_vat")
                        .HasColumnType("bit");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("tahakkuk_fee_sub_subject_id")
                        .HasColumnType("int");

                    b.Property<int>("tahakkuk_fee_subject_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_fee_sub_subject_id");

                    b.HasIndex("tahakkuk_fee_subject_id");

                    b.ToTable("TahakkukDefinitions");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDepartment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahakkuk_institution_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_institution_id");

                    b.ToTable("TahakkukDepartments");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahakkuk_department_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_department_id");

                    b.ToTable("TahakkukDirectorates");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubSubject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahakkuk_fee_subject_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_fee_subject_id");

                    b.ToTable("TahakkukFeeSubSubjects");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahakkuk_directorate_id")
                        .HasColumnType("int");

                    b.Property<int?>("tahakkuk_scale_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_directorate_id");

                    b.HasIndex("tahakkuk_scale_id");

                    b.ToTable("TahakkukFeeSubjects");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukInstitution", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahakkuk_year_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_year_id");

                    b.ToTable("TahakkukInstitutions");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukScale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("scale_value")
                        .HasColumnType("int");

                    b.Property<int>("tahakkuk_directorate_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tahakkuk_directorate_id");

                    b.ToTable("TahakkukScales");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukYear", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("district_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("district_id");

                    b.ToTable("TahakkukYears");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.District", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.City", "city")
                        .WithMany("districts")
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDefinition", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukFeeSubSubject", "tahakkuk_fee_sub_subject")
                        .WithMany()
                        .HasForeignKey("tahakkuk_fee_sub_subject_id");

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", "tahakkuk_fee_subject")
                        .WithMany()
                        .HasForeignKey("tahakkuk_fee_subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_fee_sub_subject");

                    b.Navigation("tahakkuk_fee_subject");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDepartment", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukInstitution", "tahakkuk_institution")
                        .WithMany()
                        .HasForeignKey("tahakkuk_institution_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_institution");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukDepartment", "tahakkuk_department")
                        .WithMany()
                        .HasForeignKey("tahakkuk_department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_department");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubSubject", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", "tahakkuk_fee_subject")
                        .WithMany()
                        .HasForeignKey("tahakkuk_fee_subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_fee_subject");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukFeeSubject", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", "tahakkuk_directorate")
                        .WithMany()
                        .HasForeignKey("tahakkuk_directorate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukScale", "tahakkuk_scale")
                        .WithMany()
                        .HasForeignKey("tahakkuk_scale_id");

                    b.Navigation("tahakkuk_directorate");

                    b.Navigation("tahakkuk_scale");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukInstitution", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukYear", "tahakkuk_year")
                        .WithMany()
                        .HasForeignKey("tahakkuk_year_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_year");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukScale", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.TahakkukDirectorate", "tahakkuk_directorate")
                        .WithMany()
                        .HasForeignKey("tahakkuk_directorate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tahakkuk_directorate");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.TahakkukYear", b =>
                {
                    b.HasOne("SahilPlanProje.WebApi.Entities.District", "district")
                        .WithMany()
                        .HasForeignKey("district_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("district");
                });

            modelBuilder.Entity("SahilPlanProje.WebApi.Entities.City", b =>
                {
                    b.Navigation("districts");
                });
#pragma warning restore 612, 618
        }
    }
}
